# Generated by Django 4.2.13 on 2024-05-12 17:26

from django.db import migrations, models


def data_transfer(apps, schema_editor):
    Books = apps.get_model('main', 'Book')
    for book in Books.objects.all():
        book.authors = book.author
        book.save()
    

class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="for_migrate_books", to="main.author"
            ),
        ),
        migrations.RunPython(data_transfer),
    ]
