# Generated by Django 4.2.13 on 2024-05-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_book_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(related_name="books", to="main.author"),
        ),
    ]
